development:
  cloud_name: dqxuefovm
  api_key: '114655294943445'
  api_secret: 5xpfJN4GZ8iiiNQcOF83jVMPUt4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dqxuefovm
  api_key: '114655294943445'
  api_secret: 5xpfJN4GZ8iiiNQcOF83jVMPUt4
  enhance_image_tag: true
  static_image_support: false
test:
  cloud_name: dqxuefovm
  api_key: '114655294943445'
  api_secret: 5xpfJN4GZ8iiiNQcOF83jVMPUt4
  enhance_image_tag: true
  static_image_support: false